name: Coverage

on:
  workflow_dispatch:

jobs:
  testing:
    uses: ./.github/workflows/test.yml

  deepsource-coverage-reporter:
    runs-on: ubuntu-latest
    name: DeepSource coverage reporter
    needs: testing
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-report

      - name: Report test coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: python
          coverage-file: coverage.xml
          dsn: ${{ secrets.DEEPSOURCE_DSN }}
